# Generated by Django 5.2.4 on 2025-07-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sintoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sintoma1", models.CharField(max_length=255)),
                ("sintoma2", models.CharField(max_length=255)),
                ("sintoma3", models.CharField(max_length=255)),
            ],
        ),
    ]
